name: "Setup for Android"
description: "Install dependencies for Android"

runs:
  using: "composite"
  steps:
  - name: Setup JDK 17
    uses: actions/setup-java@v3
    with:
      distribution: 'zulu'
      java-version: '17'

  - uses: actions/cache@v3
    with:
      path: ~/.gradle/caches
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Displays the Android dependencies of the project
    run: ./gradlew androidDependencies
    shell: bash

